server:
  port: 7005
spring:
  application:
    name: orderClient
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group
   #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.114:3306/sc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    #url: jdbc:mysql://localhost:3306/sc?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 1010
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.example.domain
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
eureka:
  instance:
    hostname: localhost     # eureka服务端的实力名称
  client:
    fetch-registry: true  # false表示自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    register-with-eureka: true   # false表示自己不需要向注册中心注册自己
    service-url:
     #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      # 设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
     #defaultZone: http://localhost:7004/eureka/,http://localhost:7003/eureka/    # 集群版
     defaultZone: http://localhost:7004/eureka/,http://localhost:7003/eureka/